// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleChange.Repository;

namespace ScheduleChange.Migrations
{
    [DbContext(typeof(SCContext))]
    [Migration("20210527030129_initWeb")]
    partial class initWeb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScheduleChange.Data.SCCRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Airline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BoardTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayChangeIndicator")
                        .HasColumnType("int");

                    b.Property<string>("EquipConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OffPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OffTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtherNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Overbooking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtectionPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SCType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIPNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SCCRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
